import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      ".wrangler",
      ".tanstack",
      "**/node_modules/**",
      // The backend is a separate workspace with its own eslint.config.mjs and
      // its own tsconfig; linting it from the root produces false positives.
      "apps/**",
      // Vendored/generated tooling scratch directories, not project source.
      ".local/**",
      ".opencode/**",
      ".qoder/**",
      ".commandcode/**",
      ".kilo/**",
      ".kombai/**",
      // Generated by the TanStack router plugin.
      "src/routeTree.gen.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // react-refresh only affects dev-server hot reloading, never correctness
    // or the production build. These files intentionally co-locate a component
    // with its CVA variants, its action list, or its context hook — the
    // conventional shadcn/React patterns. Splitting them to satisfy an HMR
    // heuristic would be churn for no benefit.
    files: [
      "src/components/ui/**/*.tsx",
      "src/components/common/QuickActionsMenu.tsx",
      "src/lib/store/MediaActionsContext.tsx",
      "src/components/dashboard/DashboardContext.tsx",
    ],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  eslintPluginPrettier,
);
